// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRDgdy6PeNkX4XiLmA9TRieB3JUMNHIeY',
    appId: '1:535005405064:web:3a7a7875798423fedfe43d',
    messagingSenderId: '535005405064',
    projectId: 'fedev-1e80c',
    authDomain: 'fedev-1e80c.firebaseapp.com',
    storageBucket: 'fedev-1e80c.firebasestorage.app',
    measurementId: 'G-D0P7TQ7V9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIfZldlmr31HQ9aZxO4orBGI8QZlCwPKs',
    appId: '1:535005405064:android:f05ad72f2346a523dfe43d',
    messagingSenderId: '535005405064',
    projectId: 'fedev-1e80c',
    storageBucket: 'fedev-1e80c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALsr90V6cEBd1L-mzq77phXGuCMBQK3qc',
    appId: '1:535005405064:ios:6ab8ea29191d940ddfe43d',
    messagingSenderId: '535005405064',
    projectId: 'fedev-1e80c',
    storageBucket: 'fedev-1e80c.firebasestorage.app',
    iosBundleId: 'com.example.cursoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALsr90V6cEBd1L-mzq77phXGuCMBQK3qc',
    appId: '1:535005405064:ios:6ab8ea29191d940ddfe43d',
    messagingSenderId: '535005405064',
    projectId: 'fedev-1e80c',
    storageBucket: 'fedev-1e80c.firebasestorage.app',
    iosBundleId: 'com.example.cursoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRDgdy6PeNkX4XiLmA9TRieB3JUMNHIeY',
    appId: '1:535005405064:web:9f70ca23d57f18f9dfe43d',
    messagingSenderId: '535005405064',
    projectId: 'fedev-1e80c',
    authDomain: 'fedev-1e80c.firebaseapp.com',
    storageBucket: 'fedev-1e80c.firebasestorage.app',
    measurementId: 'G-FDRSCSQ6JD',
  );

}