// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoPWrA202Aiagqt-QpbdFLnzPNU2WKET0',
    appId: '1:681333409317:web:3d5f8dc02a85efe4dc61cc',
    messagingSenderId: '681333409317',
    projectId: 'com-asesor',
    authDomain: 'com-asesor.firebaseapp.com',
    storageBucket: 'com-asesor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQNWVnKST7yiJd_fJGj7PBwWXFEAE69z4',
    appId: '1:681333409317:android:db678b791e0beaeedc61cc',
    messagingSenderId: '681333409317',
    projectId: 'com-asesor',
    storageBucket: 'com-asesor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIsBdElfhx0phxRQxTAtGxjobE1kJoiak',
    appId: '1:681333409317:ios:f4628eff8bb1edf4dc61cc',
    messagingSenderId: '681333409317',
    projectId: 'com-asesor',
    storageBucket: 'com-asesor.firebasestorage.app',
    iosBundleId: 'com.example.cursoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIsBdElfhx0phxRQxTAtGxjobE1kJoiak',
    appId: '1:681333409317:ios:f4628eff8bb1edf4dc61cc',
    messagingSenderId: '681333409317',
    projectId: 'com-asesor',
    storageBucket: 'com-asesor.firebasestorage.app',
    iosBundleId: 'com.example.cursoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoPWrA202Aiagqt-QpbdFLnzPNU2WKET0',
    appId: '1:681333409317:web:520f8549b8ca2d70dc61cc',
    messagingSenderId: '681333409317',
    projectId: 'com-asesor',
    authDomain: 'com-asesor.firebaseapp.com',
    storageBucket: 'com-asesor.firebasestorage.app',
  );
}
