// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4FQ3SnZQjKgn_OhPtLX2gpru1CT3_Sns',
    appId: '1:889280428528:web:50b1c04d57e2e45405c535',
    messagingSenderId: '889280428528',
    projectId: 'comernet-3068c',
    authDomain: 'comernet-3068c.firebaseapp.com',
    storageBucket: 'comernet-3068c.firebasestorage.app',
    measurementId: 'G-8YGKE6FX1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyPUdcKv4lyVoo8s055welnD3OR8kRa88',
    appId: '1:889280428528:android:b54976a196a868ab05c535',
    messagingSenderId: '889280428528',
    projectId: 'comernet-3068c',
    storageBucket: 'comernet-3068c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ-hLXtPQsOkdoRImp-xusdZPDs2-T7mk',
    appId: '1:889280428528:ios:8d7529a3fd84bd6c05c535',
    messagingSenderId: '889280428528',
    projectId: 'comernet-3068c',
    storageBucket: 'comernet-3068c.firebasestorage.app',
    iosBundleId: 'com.example.cursoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ-hLXtPQsOkdoRImp-xusdZPDs2-T7mk',
    appId: '1:889280428528:ios:8d7529a3fd84bd6c05c535',
    messagingSenderId: '889280428528',
    projectId: 'comernet-3068c',
    storageBucket: 'comernet-3068c.firebasestorage.app',
    iosBundleId: 'com.example.cursoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4FQ3SnZQjKgn_OhPtLX2gpru1CT3_Sns',
    appId: '1:889280428528:web:e921877582ba0e2005c535',
    messagingSenderId: '889280428528',
    projectId: 'comernet-3068c',
    authDomain: 'comernet-3068c.firebaseapp.com',
    storageBucket: 'comernet-3068c.firebasestorage.app',
    measurementId: 'G-PWV97465L3',
  );

}